ALTER TABLE users DROP COLUMN email;
ALTER TABLE users MODIFY COLUMN age VARCHAR(10);
ALTER TABLE comments DROP FOREIGN KEY fk_comments_post;
ALTER TABLE comments DROP COLUMN post_id;
ALTER TABLE users MODIFY COLUMN age VARCHAR(10);